[package]
name = "c0cc"
version = "0.1.0"
authors = ["root <lzj01071508@buaa.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"